"""add passport_number to user

Revision ID: 7524e162355b
Revises: 2e25927ae4b8
Create Date: 2026-10-09 11:02:13.280620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7524e162355b'
down_revision = '2e25927ae4b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport_number', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_passport_number'), ['passport_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_passport_number'))
        batch_op.drop_column('passport_number')

    # ### end Alembic commands ###
